Full Stack Project/server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [

    # path for about view
    path(route='about', view=views.about, name='about'),

    # path for contact us view
    path(route='contact', view=views.contact, name='contact'),

    # path for registration
    path(route='signup', view=views.registration_request, name='signup'),

    # path for login
    path(route='login', view=views.login_request, name='login'),

    # path for logout
    path(route='logout', view=views.logout_request, name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view
    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),

    # path for add a review view
    path(route='dealer/<int:dealer_id>/add-review/', view=views.add_review, name="add_review"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Full Stack Project/server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Full Stack Project/server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

class CarModel(models.Model):
    car_make = models.ForeignKey(CarMake, on_delete=models.CASCADE)
    dealer_id = models.IntegerField()
    name = models.CharField(max_length=100)
    CAR_TYPES = [
        ('Sedan', 'Sedan'),
        ('SUV', 'SUV'),
        ('WAGON', 'Wagon'),
    ]
    type = models.CharField(max_length=10, choices=CAR_TYPES)
    year = models.DateField()

    def __str__(self):
        return f"{self.year} {self.car_make.name} {self.name} {self.type}"



class CarDealer:
    def __init__(self, id, city, state, st, address, zip, lat, long, short_name, full_name):
        self.id = id
        self.city = city
        self.state=state
        self.st=st
        self.address = address
        self.zip = zip
        self.lat = lat
        self.long = long
        self.short_name = short_name
        self.full_name = full_name

    def __str__(self):
        return "Dealer name: " + self.full_name



class DealerReview:
    def __init__(self, dealership, name,review, purchase, purchase_date, car_make, car_model, car_year, sentiment, id):
        self.dealership = dealership
        self.name = name
        self.review=review
        self.purchase = purchase
        self.purchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment
        self.id = id

    def __str__(self):
        return "review: " + self.review

Full Stack Project/server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
from .models import CarDealer, DealerReview, CarMake, CarModel
from .restapis import get_dealers_from_cf, get_dealer_reviews_from_cf, post_request,get_dealer_by_id_from_cf
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json
import uuid

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create an `about` view to render a static about page
def about(request):
    return render(request, 'djangoapp/about.html')




# Create a `contact` view to return a static contact page
def contact(request):
    return render(request, 'djangoapp/contact.html')

# Create a `login_request` view to handle sign in request
def login_request(request):
    context = {}
    if request.method == "GET":
        return render(request, 'djangoapp/login.html', context)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['psw']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('djangoapp:index')
        else:
            context['message'] = "Invalid username or password."
            return render(request, 'djangoapp/login.html', context)
    else:
        return render(request, 'djangoapp/login.html', context)


# Create a `logout_request` view to handle sign out request
def logout_request(request):
    logout(request)
    return redirect('djangoapp:index')


# Create a `registration_request` view to handle sign up request
def registration_request(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    elif request.method == 'POST':
        # Check if user exists
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            User.objects.get(username=username)
            user_exist = True
        except:
            logger.error("New user")
        if not user_exist:
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            login(request, user)
            return redirect("djangoapp:index")
        else:
            context['message'] = "User already exists."
            return render(request, 'djangoapp/registration.html', context)


# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    if request.method == "GET":
        context = {}
        url = "https://eu-de.functions.appdomain.cloud/api/v1/web/28d0b867-6bcc-4fb3-a6e3-9623b43f327e/dealership-package/get-dealership"
        # Get dealers from the URL
        dealerships = get_dealers_from_cf(url)
        context['dealerships']=dealerships
        # Concat all dealer's short name
        # dealer_names = ' '.join([dealer.short_name for dealer in dealerships])
        # Return a list of dealer short name
        # return HttpResponse(dealer_names)
        return render(request, 'djangoapp/index.html', context)


# Create a `get_dealer_details` view to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    if request.method == "GET":
        context={}
        url1 = "https://eu-de.functions.appdomain.cloud/api/v1/web/28d0b867-6bcc-4fb3-a6e3-9623b43f327e/dealership-package/get-review"
        url2 = "https://eu-de.functions.appdomain.cloud/api/v1/web/28d0b867-6bcc-4fb3-a6e3-9623b43f327e/dealership-package/get-dealership"
        # Get dealers reviews from the URL
        reviews = get_dealer_reviews_from_cf(url1,dealer_id)
        dealer = get_dealer_by_id_from_cf(url2, dealer_id)
        context['reviews']=reviews
        context['dealer']=dealer
        # review_text = ' '.join([review.sentiment for review in reviews])
        # Return a list of dealer short name
        # return HttpResponse(review_text)
        return render(request, 'djangoapp/dealer_details.html', context)



# Create a `add_review` view to submit a review
def add_review(request, dealer_id):
    if request.method == "GET":
        url = "https://eu-de.functions.appdomain.cloud/api/v1/web/28d0b867-6bcc-4fb3-a6e3-9623b43f327e/dealership-package/get-dealership"
        dealer = get_dealer_by_id_from_cf(url, dealer_id)
        context = {
            "cars": CarModel.objects.all(),
            "dealer": dealer
        }
        return render(request, 'djangoapp/add_review.html', context)
    if request.method == "POST":
            form = request.POST
            review = dict()
            unique_id = uuid.uuid4()
            review["name"] = request.user.username
            review["id"] = int.from_bytes(unique_id.bytes, byteorder='big')
            review["dealership"] = dealer_id
            review["review"] = form["content"]
            review["purchase"] = form.get("purchasecheck")
            review["another"] = "field"
            if review["purchase"]:
                review["purchase_date"] = str(datetime.strptime(form.get("purchasedate"), "%Y-%m-%d"))
            car = CarModel.objects.get(pk=form["car"])
            review["car_make"] = car.car_make.name
            review["car_model"] = car.name
            review["car_year"] = car.year.strftime("%Y")
            if form.get("purchasecheck"):
                review["purchase_date"] = str(datetime.strptime(form.get("purchasedate"), "%Y-%m-%d"))
            else: 
                review["purchase_date"] = None
            url = "https://eu-de.functions.appdomain.cloud/api/v1/web/28d0b867-6bcc-4fb3-a6e3-9623b43f327e/dealership-package/post-review" 
            
            json_payload = {"review": review}
            result = post_request(url, json_payload, dealerId=dealer_id)
            if (result):
                return redirect("djangoapp:dealer_details", dealer_id=dealer_id)
            else:
                 return redirect("djangoapp:dealer_details", dealer_id=dealer_id)

Full Stack Project/server/djangoapp/templates/djangoapp/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <h1>About Us</h1>
            <p>Welcome to XYZ Car Dealership! We are your trusted source for quality cars.</p>
            <p>With years of experience, we offer a wide range of vehicles to suit your needs and preferences.</p>
            <p>Our team is dedicated to providing excellent customer service and helping you find the perfect car.</p>
        </div>
        <div class="col-md-6">
            <img src="{% static 'images/about_us_image.jpg' %}" alt="About Us" class="img-fluid">
        </div>
    </div>
</div>
{% endblock %}

Full Stack Project/server/djangoapp/templates/djangoapp/add_review.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <h1>Write a review</h1>
    <h4><i>for {{dealer.full_name}}</i></h4>
    <br>
    <!--review form -->
    <form action="/djangoapp/dealer/{{dealer.id}}/add-review/" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="content"><b>Enter the review content:</b></label>
            <textarea class="form-control" id="content" name="content" rows="2" required></textarea>
        </div>
        <div class="form-group form-check">
            <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
            <label for="purchasecheck">Did you purchase the car? </label>
        </div>
        <div class="form-group">
            <label for="car">Select your car:</label>
            <select name="car" id="car" class="form-select">
                {% for car in cars %}
                    <option selected value={{car.id}}>{{car.car_make.name}} {{car.name}} {{ car.year }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group" data-provide="datepicker">
            <h5>Select Your Purchase Date:</h5><br/>
                <div class = "input-group date" data-provide="datepicker-inline"> 
                    <input class="date-own form-control" type="date" name="purchasedate" id="purchasedate"><br>
                </div>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
<script type="text/javascript">
    $('.date-own').datepicker({
       format: 'mm/dd/yyyy'
     });
</script>
{% endblock %}

Full Stack Project/server/djangoapp/templates/djangoapp/contact.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h1>Contact Us</h1>
    <div class="row">
        <div class="col-md-6">
            <form>
                <div class="form-group">
                    <label for="name">Your Name</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="email">Your Email</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Send Message</button>
            </form>
        </div>
        <div class="col-md-6">
            <h4>Visit Us</h4>
            <p>123 Car Street</p>
            <p>City, Country</p>
            <h4>Contact Information</h4>
            <p>Email: info@example.com</p>
            <p>Phone: +1 (123) 456-7890</p>
        </div>
    </div>
</div>
{% endblock %}

Full Stack Project/server/djangoapp/templates/djangoapp/dealer_details.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <h5 class="card-title">Reviews for {{ dealer.full_name }}</h5>
    {% if reviews %}
    <div class="card-columns"> 
        {% for review in reviews %}
            <div class="card">
                {% if review.sentiment == "positive" %}
                    <img height="20px" width= "20px" class="card-img-left" src="{{MEDIA_URL}}/emoji/positive.png" alt="Positive Emoji">
                {% elif review.sentiment == "negative" %}
                    <img height="20px" width= "20px"  class="card-img-left" src="{{MEDIA_URL}}/emoji/negative.png" alt="Negative Emoji">
                {% elif review.sentiment == "neutral" %}
                    <img height="20px" width= "20px" class="card-img-left" src="{{MEDIA_URL}}/emoji/neutral.png" alt="Neutral Emoji">
                {% endif %}
                <div class="card-body"> 
                    <h5 class="card-title">{{ review.name }}, {{ review.car_model }}</h5>
                    <h5 class="card-title">{{ review.car_year }}</h5>
                    <p class="card-text">{{ review.review }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <p class="card-text">this dealer has no reviews yet</p>
    {% endif %}
    {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'djangoapp:add_review' dealer.id %}""><b>Write a car review</b></a>
    {% endif %}
</div>
{% endblock %}

Full Stack Project/server/djangoapp/templates/djangoapp/index.html
{% extends "base.html" %}

{% block content %}
    <!-- Index page content here -->
    <h1>Welcome to our website!</h1>
    <p>Available Dealerships</p>
    <table class="table" id="table" data-filter-control="true">
        <thead>
            <tr>
                <th data-field="id">ID</th>
                <th data-field="full_name">Dealer Name</th>
                <th data-field="city">City</th>
                <th data-field="address">Address</th>
                <th data-field="zip">Zip</th>
                <th data-field="state" data-filter-control="select">State</th>
            </tr>
        </thead>
        <tbody>
            {% for dealer in dealerships %}
                <tr>
                    <td>{{dealer.id}}</td>
                    <td><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                    <td>{{dealer.city}}</td>
                    <td>{{dealer.address}}</td>
                    <td>{{dealer.zip}}</td>
                    <td>{{dealer.st}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <script>
        $(document).ready(function() {
            $('#table').bootstrapTable();
        });
    </script>
{% endblock %}

Full Stack Project/server/djangoapp/templates/djangoapp/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="d-flex align-items-center justify-content-center" style="min-height: calc(100vh - 100px);">
    <div >
<form action="{% url 'djangoapp:login' %}" method="post">
    {% csrf_token %}
        <h1>Login</h1>
        <hr>
        <div class="form-group"> <!--Style second div with .form-group class -->
          <label for="username"><b>User Name</b></label>
          <input id="username" class = "form-control" type="text" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
          <label for="psw"><b>Password</b></label>
          <input id="psw" class = "form-control" type="password"  placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
        </div>
        {% if message %}
          <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
            {{ message }}
          </div>
        {% endif %}
        <button class="btn btn-primary" type="submit">Login</button> <!--Style button with .btn and .btn-primary class -->
    
</form>
</div>
</div>
{% endblock %}

Full Stack Project/server/djangoapp/templates/djangoapp/registration.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="d-flex align-items-center justify-content-center" style="min-height: calc(100vh - 100px);">
    <div >
<form action="{% url 'djangoapp:signup' %}" method="post">
    <div class="container"> <!--Style root div with .container class -->
        {% csrf_token %}
        <h1>Sign Up</h1>
        <hr>
        <div class="form-group"> <!--Style second div with .form-group class -->
            <label for="username"><b>User Name</b></label>
            <input type="text" class="form-control" placeholder="Enter User Name: " name="username" required> <!--Style input with .form-control class -->
            <label for="firstname"><b>First Name</b></label>
            <input type="text" class="form-control" placeholder="Enter First Name: " name="firstname" required> <!--Style input with .form-control class -->
            <label for="lastname"><b>Last Name</b></label>
            <input type="text" class="form-control" placeholder="Enter Last Name: " name="lastname" required> <!--Style input with .form-control class -->
            <label for="psw"><b>Password</b></label>
            <input type="password" class="form-control" placeholder="Enter Password: " name="psw" required> <!--Style input with .form-control class -->
            {% if message %}
            <div class="alert alert-warning"> <!--Style the message paragraph with .alert and .alert-warning class -->
                {{ message }}
            </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">Sign up</button> <!--Style button with .btn and .btn-primary class -->
        </div>
    </div>
</form>
</div>
</div>
{% endblock %}